application: lluncorstock
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /img
  static_dir: img

- url: /test_data
  static_dir: test_data

- url: /js
  static_dir: js

- url: /proj/education/js
  static_dir: proj/education/js

- url: /proj/games/popnumbers
  static_dir: proj/games/popnumbers

- url: /css
  static_dir: css

- url: /.*
  script: index.py

libraries:
- name: django
  version: "1.3"
- name: numpy
  version: "1.6.1"
