application: teacherlunk
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /img
  static_dir: img

- url: /test_data
  static_dir: test_data

- url: /js
  static_dir: js

- url: /proj/education/js
  static_dir: proj/education/js

- url: /proj/games/popnumbers
  static_dir: proj/games/popnumbers

- url: /proj/games/bubblepop
  static_dir: proj/games/bubblepop

- url: /proj/stats/js
  static_dir: proj/stats/js

- url: /proj/easydo/js
  static_dir: proj/easydo/js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

# Getting bootstrap assets.
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /.*
  script: index.py

libraries:
- name: django
  version: "1.3"
- name: numpy
  version: "1.6.1"
